import {Contact} from './contact/contact.component';

export const CONTACTS: Contact[] = [
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '123145', name: 'Favorito', email: '', phone: '', address: '', notes: '', isFav: true},
    {id: '464787', name: 'Gabriel', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '5645121', name: 'No favorito', email: '', phone: '', address: '', notes: '', isFav: false},
    {id: '488923113', name: 'Ana', email: '', phone: '', address: '', notes: '', isFav: false}
]